# Generated by Django 4.0.5 on 2022-06-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steps',
        ),
    ]
