# Generated by Django 4.0.5 on 2022-06-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_steps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'TestRoles'},
        ),
        migrations.AlterModelOptions(
            name='steps',
            options={'verbose_name_plural': 'TestRoles'},
        ),
    ]
