# Generated by Django 4.0.5 on 2022-06-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0004_alter_activity_options_alter_steps_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activity'},
        ),
        migrations.AlterModelOptions(
            name='steps',
            options={'verbose_name_plural': 'Steps'},
        ),
    ]
